[toolchain]
anchor_version = ".0.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
veil_vault = "4CwAfhsw9RwDex82Kqmz3NXGhvEM7Uj8MXKHTfy5V4MT"

[programs.localnet]
veil_vault = "5Jn23ZQaF8LVbm5WQASc7QWcAhq9QPLJQGFxmC2gUwgB"

[provider]
cluster = "devnet"
wallet = "/home/sane/.config/solana/id.json"

[workspace]
members = ["program"]

[scripts]
test = "npx ts-mocha -p ./tests/tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
